"""empty message

Revision ID: 319b62464bc5
Revises: 7065c3c09ca3
Create Date: 2020-04-02 00:01:47.389366

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '319b62464bc5'
down_revision = '7065c3c09ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('geom', geoalchemy2.Geometry(geometry_type='POINT', srid=4326), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'geom')
    # ### end Alembic commands ###
