"""empty message

Revision ID: 41362230d704
Revises: c42102f9f49e
Create Date: 2020-03-28 17:30:54.494666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41362230d704'
down_revision = 'c42102f9f49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('modified', sa.DateTime(), nullable=True))
    op.drop_column('items', 'updated')
    op.add_column('users', sa.Column('modified', sa.DateTime(), nullable=True))
    op.drop_column('users', 'updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'modified')
    op.add_column('items', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('items', 'modified')
    # ### end Alembic commands ###
