"""empty message

Revision ID: 7065c3c09ca3
Revises: 41362230d704
Create Date: 2020-03-29 23:30:16.270422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7065c3c09ca3'
down_revision = '41362230d704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('address', sa.String(length=1024), nullable=True))
    op.drop_column('locations', 'addres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('addres', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('locations', 'address')
    # ### end Alembic commands ###
